[package]
name = "entradasaida"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
listadetarefas = {path ="../listadetarefas"}
chrono = "0.4.37"
serde_json = "1.0.115"
mock = {path ="../mock"}